language: python
python:
  - "2.7"
install:
  # this fixes SemLock issues on travis
  - "pip install cython"
  - "make test_setup"
  - "pip install redis leaderboard==$LEADERBOARD_VERSION"
  - "pip install . --no-deps"
env:
  matrix: 
    - COMMAND="make test" $LEADERBOARD_VERSION="3.5.0"
    - COMMAND="make cybuild test" $LEADERBOARD_VERSION="3.5.0"
services:
  - redis-server
script: "$COMMAND"
